In [3]:
import pandas as pd

In [4]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['A','B','C'],index=['x','y','z'])

In [5]:
df.head()

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [6]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [7]:
df.index

Index(['x', 'y', 'z'], dtype='object')

In [8]:
df.index.tolist()

['x', 'y', 'z']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [10]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [11]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [12]:
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [13]:
df['A'].unique()

array([1, 4, 7])

In [14]:
coffee=pd.read_csv(r"C:\Users\Chaitanya\OneDrive\Desktop\NTIN SIR\coffee.csv")

In [15]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [16]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [17]:
coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [18]:
olympic=pd.read_excel(r"C:\Users\Chaitanya\Downloads\olympics-data.xlsx")

In [19]:
olympic.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [20]:
bios=pd.read_csv(r"C:\Users\Chaitanya\Downloads\bios.csv")

In [21]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [22]:
bios.to_excel

<bound method NDFrame.to_excel of         athlete_id                   name   born_date        born_city  \
0                1  Jean-François Blanchy  1886-12-12         Bordeaux
1                2         Arnaud Boetsch  1969-04-01           Meulan
2                3           Jean Borotra  1898-08-13         Biarritz
3                4        Jacques Brugnon  1895-05-11      Paris VIIIe
4                5           Albert Canet  1878-04-17       Wandsworth
...            ...                    ...         ...              ...
145495      149222      Polina Luchnikova  2002-01-30            Serov
145496      149223    Valeriya Merkusheva  1999-09-20  Moskva (Moscow)
145497      149224        Yuliya Smirnova  1998-05-08           Kotlas
145498      149225         André Foussard  1899-05-19            Niort
145499      149814          Bill Phillips  1913-07-15     Dulwich Hill

                 born_region born_country        NOC  height_cm  weight_kg  \
0                    Gironde          FRA     France        NaN        NaN
1                   Yvelines          FRA     France      183.0       76.0
2       Pyrénées-Atlantiques          FRA     France      183.0       76.0
3                      Paris          FRA     France      168.0       64.0
4                    England          GBR     France        NaN        NaN
...                      ...          ...        ...        ...        ...
145495            Sverdlovsk          RUS        ROC      167.0       61.0
145496                Moskva          RUS        ROC      168.0       65.0
145497           Arkhangelsk          RUS        ROC      163.0       55.0
145498           Deux-Sèvres          FRA     France      166.0        NaN
145499       New South Wales          AUS  Australia        NaN        NaN

         died_date
0       1960-10-02
1              NaN
2       1994-07-17
3       1978-03-20
4       1930-07-25
...            ...
145495         NaN
145496         NaN
145497         NaN
145498  1986-03-18
145499  2003-10-20

[145500 rows x 10 columns]>

In [23]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [24]:
coffee.loc[0:5]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25

In [25]:
coffee.loc[[0,1,5]]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
5  Wednesday       Latte          25

In [26]:
coffee.loc[:,["Day","Units Sold"]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [27]:
coffee.iloc[:,[0,2]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [28]:
coffee.index=coffee['Day']

In [29]:
coffee

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [30]:
coffee.loc['Monday':'Wednesday','Units Sold']

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Name: Units Sold, dtype: int64

In [31]:
coffee = coffee.reset_index(drop=True)
coffee.at[0,'Units Sold']

np.int64(25)

In [32]:
coffee.iat[0,0]

'Monday'

In [33]:
coffee.sort_values("Units Sold",ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [34]:
coffee.sort_values(["Coffee Type","Units Sold"],ascending=[0,1])

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
5   Wednesday       Latte          25
7    Thursday       Latte          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
0      Monday    Espresso          25
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [35]:
for index,row in coffee.iterrows():
    print(index)
    print(row)
    print('\n\n\n')

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object




1
Day            Monday
Coffee Type     Latte
Units Sold         15
Name: 1, dtype: object




2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object




3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object




4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object




5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object




6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object




7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object




8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object




9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object




10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object




11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object




12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object




13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object

In [36]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [37]:
bios.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [38]:
bios.loc[bios['height_cm']>215,['name','height_cm'] ]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [39]:
bios.loc[(bios['height_cm']>215) & (bios['born_country']=='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [40]:
bios[bios['name'].str.contains('Keith')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [41]:
bios[bios['born_country'].isin(['USA','FRA','GRB']) & (bios['name'].str.startswith("Keith"))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

In [42]:
coffee['price']=4.99

In [43]:
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [44]:
import numpy as np
coffee['new__price']=np.where('Coffee Type'=='Espresso',3.99,5.99)

In [45]:
coffee

          Day Coffee Type  Units Sold  price  new__price
0      Monday    Espresso          25   4.99        5.99
1      Monday       Latte          15   4.99        5.99
2     Tuesday    Espresso          30   4.99        5.99
3     Tuesday       Latte          20   4.99        5.99
4   Wednesday    Espresso          35   4.99        5.99
5   Wednesday       Latte          25   4.99        5.99
6    Thursday    Espresso          40   4.99        5.99
7    Thursday       Latte          30   4.99        5.99
8      Friday    Espresso          45   4.99        5.99
9      Friday       Latte          35   4.99        5.99
10   Saturday    Espresso          45   4.99        5.99
11   Saturday       Latte          35   4.99        5.99
12     Sunday    Espresso          45   4.99        5.99
13     Sunday       Latte          35   4.99        5.99

In [46]:
coffee.drop(columns=['price'])

          Day Coffee Type  Units Sold  new__price
0      Monday    Espresso          25        5.99
1      Monday       Latte          15        5.99
2     Tuesday    Espresso          30        5.99
3     Tuesday       Latte          20        5.99
4   Wednesday    Espresso          35        5.99
5   Wednesday       Latte          25        5.99
6    Thursday    Espresso          40        5.99
7    Thursday       Latte          30        5.99
8      Friday    Espresso          45        5.99
9      Friday       Latte          35        5.99
10   Saturday    Espresso          45        5.99
11   Saturday       Latte          35        5.99
12     Sunday    Espresso          45        5.99
13     Sunday       Latte          35        5.99

In [47]:
coffee['revenue']=coffee['Units Sold']* coffee['price']

In [48]:
coffee

          Day Coffee Type  Units Sold  price  new__price  revenue
0      Monday    Espresso          25   4.99        5.99   124.75
1      Monday       Latte          15   4.99        5.99    74.85
2     Tuesday    Espresso          30   4.99        5.99   149.70
3     Tuesday       Latte          20   4.99        5.99    99.80
4   Wednesday    Espresso          35   4.99        5.99   174.65
5   Wednesday       Latte          25   4.99        5.99   124.75
6    Thursday    Espresso          40   4.99        5.99   199.60
7    Thursday       Latte          30   4.99        5.99   149.70
8      Friday    Espresso          45   4.99        5.99   224.55
9      Friday       Latte          35   4.99        5.99   174.65
10   Saturday    Espresso          45   4.99        5.99   224.55
11   Saturday       Latte          35   4.99        5.99   174.65
12     Sunday    Espresso          45   4.99        5.99   224.55
13     Sunday       Latte          35   4.99        5.99   174.65

In [49]:
bios_new=bios.copy()

In [50]:
bios_new['first_name']=bios_new['name'].str.split(' ').str[0]

In [51]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [52]:
bios_new.query('first_name =="Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

In [53]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
 10  first_name    145500 non-null  object
dtypes: float64(2), int64(1), object(8)
memory usage: 12.2+ MB

In [54]:
bios_new['born_datetime']=pd.to_datetime(bios_new['born_date'])

In [55]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15

In [56]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  object
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  first_name     145500 non-null  object
 11  born_datetime  143693 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 13.3+ MB

In [57]:
bios_new['born_year']=bios_new['born_datetime'].dt.year

In [58]:
bios_new[['name','born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [59]:
bios_new.to_csv('./date/bios_new.csv',index=False)

OSError: Cannot save file into a non-existent directory: 'date'

In [ ]:
bios['height_category']=bios['height_cm'].apply(lambda x:'Short' if x<165 else( 'AVERAGE' if x<185 else 'Tall'))

In [ ]:
bios.head()

In [ ]:
def categorize_athlete(row):
    if(row['height_cm']<175 and row['weight_kg']<70):
        return 'Leightweight'
    elif(row['height_cm']<180 and row['weight_kg']<=80):
        return 'Middleweight'
    else:
        return 'Heavyweight'
bios['Category']=bios.apply(categorize_athlete,axis=1)

In [ ]:
bios.head()

In [ ]:
# Load your main athlete data
bios = pd.read_excel(r"C:\Users\Chaitanya\Downloads\olympics-data.xlsx")

# Load the region mapping file (get this from Keith's GitHub)
nocs = pd.read_csv(r"C:\Users\Chaitanya\Downloads\noc_regions.csv")

In [ ]:
# This is the exact code from the video
df = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left')

# Show the results
df.head()

In [ ]:
bios_new.rename(columns={'region':'born_country_full'},inplace=True)

In [ ]:
bios_new.head()

In [ ]:
usa=bios[bios['born_country']=='USA'].copy()

In [ ]:
gbr=bios[bios['born_country']=='GBR'].copy()

In [ ]:
gbr.head()

In [ ]:
usa.tail()

In [ ]:
new_df=pd.concat([usa,gbr])

In [ ]:
new_df.head()

In [ ]:
results=pd.read_csv(r"C:\Users\Chaitanya\Downloads\results.csv")
combined_df=pd.merge(results,bios,on='athlete_id',how='left')

In [ ]:
combined_df.head()

In [61]:
import numpy as np
coffee.loc[[0,1],'Units Sold']=np.nan

In [62]:
coffee

          Day Coffee Type  Units Sold  price  new__price  revenue
0      Monday    Espresso         NaN   4.99        5.99   124.75
1      Monday       Latte         NaN   4.99        5.99    74.85
2     Tuesday    Espresso        30.0   4.99        5.99   149.70
3     Tuesday       Latte        20.0   4.99        5.99    99.80
4   Wednesday    Espresso        35.0   4.99        5.99   174.65
5   Wednesday       Latte        25.0   4.99        5.99   124.75
6    Thursday    Espresso        40.0   4.99        5.99   199.60
7    Thursday       Latte        30.0   4.99        5.99   149.70
8      Friday    Espresso        45.0   4.99        5.99   224.55
9      Friday       Latte        35.0   4.99        5.99   174.65
10   Saturday    Espresso        45.0   4.99        5.99   224.55
11   Saturday       Latte        35.0   4.99        5.99   174.65
12     Sunday    Espresso        45.0   4.99        5.99   224.55
13     Sunday       Latte        35.0   4.99        5.99   174.65

In [63]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
price          0
new__price     0
revenue        0
dtype: int64

In [65]:
coffee.fillna(coffee['Units Sold'].mean())

          Day Coffee Type  Units Sold  price  new__price  revenue
0      Monday    Espresso        35.0   4.99        5.99   124.75
1      Monday       Latte        35.0   4.99        5.99    74.85
2     Tuesday    Espresso        30.0   4.99        5.99   149.70
3     Tuesday       Latte        20.0   4.99        5.99    99.80
4   Wednesday    Espresso        35.0   4.99        5.99   174.65
5   Wednesday       Latte        25.0   4.99        5.99   124.75
6    Thursday    Espresso        40.0   4.99        5.99   199.60
7    Thursday       Latte        30.0   4.99        5.99   149.70
8      Friday    Espresso        45.0   4.99        5.99   224.55
9      Friday       Latte        35.0   4.99        5.99   174.65
10   Saturday    Espresso        45.0   4.99        5.99   224.55
11   Saturday       Latte        35.0   4.99        5.99   174.65
12     Sunday    Espresso        45.0   4.99        5.99   224.55
13     Sunday       Latte        35.0   4.99        5.99   174.65

In [66]:
##HANDLING NULL VALUES
import numpy as np
coffee.loc[[0,1],'Units Sold']=15

In [67]:
coffee.loc[[2,3],'Units Sold']=np.nan

In [68]:
coffee

          Day Coffee Type  Units Sold  price  new__price  revenue
0      Monday    Espresso        15.0   4.99        5.99   124.75
1      Monday       Latte        15.0   4.99        5.99    74.85
2     Tuesday    Espresso         NaN   4.99        5.99   149.70
3     Tuesday       Latte         NaN   4.99        5.99    99.80
4   Wednesday    Espresso        35.0   4.99        5.99   174.65
5   Wednesday       Latte        25.0   4.99        5.99   124.75
6    Thursday    Espresso        40.0   4.99        5.99   199.60
7    Thursday       Latte        30.0   4.99        5.99   149.70
8      Friday    Espresso        45.0   4.99        5.99   224.55
9      Friday       Latte        35.0   4.99        5.99   174.65
10   Saturday    Espresso        45.0   4.99        5.99   224.55
11   Saturday       Latte        35.0   4.99        5.99   174.65
12     Sunday    Espresso        45.0   4.99        5.99   224.55
13     Sunday       Latte        35.0   4.99        5.99   174.65

In [71]:
coffee['Units Sold']=coffee['Units Sold'].interpolate()

In [72]:
coffee

          Day Coffee Type  Units Sold  price  new__price  revenue
0      Monday    Espresso   15.000000   4.99        5.99   124.75
1      Monday       Latte   15.000000   4.99        5.99    74.85
2     Tuesday    Espresso   21.666667   4.99        5.99   149.70
3     Tuesday       Latte   28.333333   4.99        5.99    99.80
4   Wednesday    Espresso   35.000000   4.99        5.99   174.65
5   Wednesday       Latte   25.000000   4.99        5.99   124.75
6    Thursday    Espresso   40.000000   4.99        5.99   199.60
7    Thursday       Latte   30.000000   4.99        5.99   149.70
8      Friday    Espresso   45.000000   4.99        5.99   224.55
9      Friday       Latte   35.000000   4.99        5.99   174.65
10   Saturday    Espresso   45.000000   4.99        5.99   224.55
11   Saturday       Latte   35.000000   4.99        5.99   174.65
12     Sunday    Espresso   45.000000   4.99        5.99   224.55
13     Sunday       Latte   35.000000   4.99        5.99   174.65

In [73]:
coffee.loc[[2,3],'Units Sold']=np.nan

In [74]:
coffee

          Day Coffee Type  Units Sold  price  new__price  revenue
0      Monday    Espresso        15.0   4.99        5.99   124.75
1      Monday       Latte        15.0   4.99        5.99    74.85
2     Tuesday    Espresso         NaN   4.99        5.99   149.70
3     Tuesday       Latte         NaN   4.99        5.99    99.80
4   Wednesday    Espresso        35.0   4.99        5.99   174.65
5   Wednesday       Latte        25.0   4.99        5.99   124.75
6    Thursday    Espresso        40.0   4.99        5.99   199.60
7    Thursday       Latte        30.0   4.99        5.99   149.70
8      Friday    Espresso        45.0   4.99        5.99   224.55
9      Friday       Latte        35.0   4.99        5.99   174.65
10   Saturday    Espresso        45.0   4.99        5.99   224.55
11   Saturday       Latte        35.0   4.99        5.99   174.65
12     Sunday    Espresso        45.0   4.99        5.99   224.55
13     Sunday       Latte        35.0   4.99        5.99   174.65

In [75]:
coffee.dropna()

          Day Coffee Type  Units Sold  price  new__price  revenue
0      Monday    Espresso        15.0   4.99        5.99   124.75
1      Monday       Latte        15.0   4.99        5.99    74.85
4   Wednesday    Espresso        35.0   4.99        5.99   174.65
5   Wednesday       Latte        25.0   4.99        5.99   124.75
6    Thursday    Espresso        40.0   4.99        5.99   199.60
7    Thursday       Latte        30.0   4.99        5.99   149.70
8      Friday    Espresso        45.0   4.99        5.99   224.55
9      Friday       Latte        35.0   4.99        5.99   174.65
10   Saturday    Espresso        45.0   4.99        5.99   224.55
11   Saturday       Latte        35.0   4.99        5.99   174.65
12     Sunday    Espresso        45.0   4.99        5.99   224.55
13     Sunday       Latte        35.0   4.99        5.99   174.65

In [76]:
coffee[coffee['Units Sold'].isna()]

       Day Coffee Type  Units Sold  price  new__price  revenue
2  Tuesday    Espresso         NaN   4.99        5.99    149.7
3  Tuesday       Latte         NaN   4.99        5.99     99.8

In [77]:
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold  price  new__price  revenue
0      Monday    Espresso        15.0   4.99        5.99   124.75
1      Monday       Latte        15.0   4.99        5.99    74.85
4   Wednesday    Espresso        35.0   4.99        5.99   174.65
5   Wednesday       Latte        25.0   4.99        5.99   124.75
6    Thursday    Espresso        40.0   4.99        5.99   199.60
7    Thursday       Latte        30.0   4.99        5.99   149.70
8      Friday    Espresso        45.0   4.99        5.99   224.55
9      Friday       Latte        35.0   4.99        5.99   174.65
10   Saturday    Espresso        45.0   4.99        5.99   224.55
11   Saturday       Latte        35.0   4.99        5.99   174.65
12     Sunday    Espresso        45.0   4.99        5.99   224.55
13     Sunday       Latte        35.0   4.99        5.99   174.65

In [78]:
##AGGREGATING DATA
bios['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Bodrogkisfalud        1
Ternberg              1
Klaus                 1
Plaški                1
Dulwich Hill          1
Name: count, Length: 22368, dtype: int64

In [79]:
bios[bios['born_country']=='USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
South Carolina            50
Maine                     50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [80]:
bios[bios['born_country']=='USA']['born_region'].value_counts().tail()

born_region
South Dakota     27
West Virginia    24
Delaware         22
North Dakota     16
Wyoming          14
Name: count, dtype: int64

In [81]:
bios[bios['born_country']=='USA']['born_region'].value_counts().tail(25)

born_region
Utah              91
Missouri          91
North Carolina    86
Arizona           83
New Hampshire     83
Vermont           68
Mississippi       66
Alabama           64
Kentucky          62
Tennessee         62
Nebraska          60
Rhode Island      56
Montana           55
South Carolina    50
Maine             50
Alaska            45
Arkansas          42
Idaho             41
New Mexico        38
Nevada            36
South Dakota      27
West Virginia     24
Delaware          22
North Dakota      16
Wyoming           14
Name: count, dtype: int64

In [82]:
coffee['Units Sold']=coffee['Units Sold'].interpolate()

In [83]:
coffee

          Day Coffee Type  Units Sold  price  new__price  revenue
0      Monday    Espresso   15.000000   4.99        5.99   124.75
1      Monday       Latte   15.000000   4.99        5.99    74.85
2     Tuesday    Espresso   21.666667   4.99        5.99   149.70
3     Tuesday       Latte   28.333333   4.99        5.99    99.80
4   Wednesday    Espresso   35.000000   4.99        5.99   174.65
5   Wednesday       Latte   25.000000   4.99        5.99   124.75
6    Thursday    Espresso   40.000000   4.99        5.99   199.60
7    Thursday       Latte   30.000000   4.99        5.99   149.70
8      Friday    Espresso   45.000000   4.99        5.99   224.55
9      Friday       Latte   35.000000   4.99        5.99   174.65
10   Saturday    Espresso   45.000000   4.99        5.99   224.55
11   Saturday       Latte   35.000000   4.99        5.99   174.65
12     Sunday    Espresso   45.000000   4.99        5.99   224.55
13     Sunday       Latte   35.000000   4.99        5.99   174.65

In [84]:
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    246.666667
Latte       203.333333
Name: Units Sold, dtype: float64

In [86]:
coffee.groupby(['Coffee Type','Day']).agg({'Units Sold':'sum','price':'mean'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday      45.000000   4.99
            Monday      15.000000   4.99
            Saturday    45.000000   4.99
            Sunday      45.000000   4.99
            Thursday    40.000000   4.99
            Tuesday     21.666667   4.99
            Wednesday   35.000000   4.99
Latte       Friday      35.000000   4.99
            Monday      15.000000   4.99
            Saturday    35.000000   4.99
            Sunday      35.000000   4.99
            Thursday    30.000000   4.99
            Tuesday     28.333333   4.99
            Wednesday   25.000000   4.99

In [87]:
pivot=coffee.pivot(columns='Coffee Type',index='Day',values='revenue')

In [88]:
pivot

Coffee Type  Espresso   Latte
Day
Friday         224.55  174.65
Monday         124.75   74.85
Saturday       224.55  174.65
Sunday         224.55  174.65
Thursday       199.60  149.70
Tuesday        149.70   99.80
Wednesday      174.65  124.75

In [89]:
pivot.sum

<bound method DataFrame.sum of Coffee Type  Espresso   Latte
Day
Friday         224.55  174.65
Monday         124.75   74.85
Saturday       224.55  174.65
Sunday         224.55  174.65
Thursday       199.60  149.70
Tuesday        149.70   99.80
Wednesday      174.65  124.75>

In [91]:
pivot.sum(axis=1)

Day
Friday       399.2
Monday       199.6
Saturday     399.2
Sunday       399.2
Thursday     349.3
Tuesday      249.5
Wednesday    299.4
dtype: float64

In [93]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [94]:
bios['born_date']=pd.to_datetime(bios['born_date'])

In [95]:
bios['month_born']=bios['born_date'].dt.month
bios['year_born']=bios['born_date'].dt.year
bios.groupby([bios['month_born'],bios['year_born']])['name'].count().reset_index().sort_values('name',ascending=False)

      month_born  year_born  name
124          1.0     1970.0   239
126          1.0     1972.0   229
129          1.0     1975.0   227
140          1.0     1986.0   227
139          1.0     1985.0   225
...          ...        ...   ...
1262         9.0     1852.0     1
1264         9.0     1854.0     1
1265         9.0     1855.0     1
1267         9.0     1857.0     1
1884        12.0     2006.0     1

[1885 rows x 3 columns]

In [96]:
coffee['yesterday_revenue']=coffee['revenue'].shift(2)

In [97]:
coffee

,Day,Coffee Type,Units Sold,price,new__price,revenue,yesterday_revenue
0,Monday,Espresso,15.000000,4.99,5.99,124.75,NaN
1,Monday,Latte,15.000000,4.99,5.99,74.85,NaN
2,Tuesday,Espresso,21.666667,4.99,5.99,149.70,124.75
3,Tuesday,Latte,28.333333,4.99,5.99,99.80,74.85
4,Wednesday,Espresso,35.000000,4.99,5.99,174.65,149.70
5,Wednesday,Latte,25.000000,4.99,5.99,124.75,99.80
6,Thursday,Espresso,40.000000,4.99,5.99,199.60,174.65
7,Thursday,Latte,30.000000,4.99,5.99,149.70,124.75
8,Friday,Espresso,45.000000,4.99,5.99,224.55,199.60
9,Friday,Latte,35.000000,4.99,5.99,174.65,149.70
10,Saturday,Espresso,45.000000,4.99,5.99,224.55,224.55
11,Saturday,Latte,35.000000,4.99,5.99,174.65,174.65
12,Sunday,Espresso,45.000000,4.99,5.99,224.55,224.55
13,Sunday,Latte,35.000000,4.99,5.99,174.65,174.65

In [98]:
coffee['pct_change']=coffee['revenue']/coffee['yesterday_revenue']*100

In [99]:
coffee

,Day,Coffee Type,Units Sold,price,new__price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,15.000000,4.99,5.99,124.75,NaN,NaN
1,Monday,Latte,15.000000,4.99,5.99,74.85,NaN,NaN
2,Tuesday,Espresso,21.666667,4.99,5.99,149.70,124.75,120.000000
3,Tuesday,Latte,28.333333,4.99,5.99,99.80,74.85,133.333333
4,Wednesday,Espresso,35.000000,4.99,5.99,174.65,149.70,116.666667
5,Wednesday,Latte,25.000000,4.99,5.99,124.75,99.80,125.000000
6,Thursday,Espresso,40.000000,4.99,5.99,199.60,174.65,114.285714
7,Thursday,Latte,30.000000,4.99,5.99,149.70,124.75,120.000000
8,Friday,Espresso,45.000000,4.99,5.99,224.55,199.60,112.500000
9,Friday,Latte,35.000000,4.99,5.99,174.65,149.70,116.666667
10,Saturday,Espresso,45.000000,4.99,5.99,224.55,224.55,100.000000
11,Saturday,Latte,35.000000,4.99,5.99,174.65,174.65,100.000000
12,Sunday,Espresso,45.000000,4.99,5.99,224.55,224.55,100.000000
13,Sunday,Latte,35.000000,4.99,5.99,174.65,174.65,100.000000

In [100]:
bios['height_rank']=bios['height_cm'].rank()

In [101]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,month_born,year_born,height_rank
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,12.0,1886.0,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,4.0,1969.0,79054.5
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,8.0,1898.0,79054.5
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,5.0,1895.0,22677.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,4.0,1878.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,1.0,2002.0,19463.5
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,9.0,1999.0,22677.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,5.0,1998.0,10346.5
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,5.0,1899.0,17377.5
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,7.0,1913.0,NaN

In [103]:
bios.sort_values(['height_rank'],ascending=False)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,month_born,year_born,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,9.0,1980.0,106651.0
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,2.0,1952.0,106649.5
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,12.0,1964.0,106649.5
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,11.0,1975.0,106647.0
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN,11.0,1987.0,106647.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,6.0,1995.0,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,12.0,1989.0,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,4.0,1927.0,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,8.0,1998.0,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,7.0,1913.0,NaN

In [104]:
bios.sort_values(['height_rank'])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,month_born,year_born,height_rank
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN,10.0,1953.0,1.5
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,5.0,1963.0,1.5
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,6.0,1967.0,3.0
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,9.0,1949.0,4.5
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,12.0,1959.0,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,6.0,1995.0,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,12.0,1989.0,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,4.0,1927.0,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,8.0,1998.0,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,7.0,1913.0,NaN

In [105]:
coffee['cummulative_revenue']=coffee['revenue'].cumsum()

In [106]:
coffee

,Day,Coffee Type,Units Sold,price,new__price,revenue,yesterday_revenue,pct_change,cummulative_revenue
0,Monday,Espresso,15.000000,4.99,5.99,124.75,NaN,NaN,124.75
1,Monday,Latte,15.000000,4.99,5.99,74.85,NaN,NaN,199.60
2,Tuesday,Espresso,21.666667,4.99,5.99,149.70,124.75,120.000000,349.30
3,Tuesday,Latte,28.333333,4.99,5.99,99.80,74.85,133.333333,449.10
4,Wednesday,Espresso,35.000000,4.99,5.99,174.65,149.70,116.666667,623.75
5,Wednesday,Latte,25.000000,4.99,5.99,124.75,99.80,125.000000,748.50
6,Thursday,Espresso,40.000000,4.99,5.99,199.60,174.65,114.285714,948.10
7,Thursday,Latte,30.000000,4.99,5.99,149.70,124.75,120.000000,1097.80
8,Friday,Espresso,45.000000,4.99,5.99,224.55,199.60,112.500000,1322.35
9,Friday,Latte,35.000000,4.99,5.99,174.65,149.70,116.666667,1497.00
10,Saturday,Espresso,45.000000,4.99,5.99,224.55,224.55,100.000000,1721.55
11,Saturday,Latte,35.000000,4.99,5.99,174.65,174.65,100.000000,1896.20
12,Sunday,Espresso,45.000000,4.99,5.99,224.55,224.55,100.000000,2120.75
13,Sunday,Latte,35.000000,4.99,5.99,174.65,174.65,100.000000,2295.40

In [108]:
latte=coffee[coffee['Coffee Type']=="Latte"].copy()
latte['3day']=latte['Units Sold'].rolling(3).sum()

In [110]:
latte

,Day,Coffee Type,Units Sold,price,new__price,revenue,yesterday_revenue,pct_change,cummulative_revenue,3day
1,Monday,Latte,15.000000,4.99,5.99,74.85,NaN,NaN,199.6,NaN
3,Tuesday,Latte,28.333333,4.99,5.99,99.80,74.85,133.333333,449.1,NaN
5,Wednesday,Latte,25.000000,4.99,5.99,124.75,99.80,125.000000,748.5,68.333333
7,Thursday,Latte,30.000000,4.99,5.99,149.70,124.75,120.000000,1097.8,83.333333
9,Friday,Latte,35.000000,4.99,5.99,174.65,149.70,116.666667,1497.0,90.000000
11,Saturday,Latte,35.000000,4.99,5.99,174.65,174.65,100.000000,1896.2,100.000000
13,Sunday,Latte,35.000000,4.99,5.99,174.65,174.65,100.000000,2295.4,105.000000

In [112]:
pd.__version__

'2.3.3'