In [1]:
#install pandas
!pip install pandas

Requirement already satisfied: pandas in c:\users\chaitanya\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\chaitanya\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\chaitanya\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\chaitanya\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\chaitanya\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\chaitanya\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
#import pandas
import pandas as pd

In [6]:
#1.create DataFrame
df=pd.DataFrame([11,22,33],columns=['Col'])
df

   Col
0   11
1   22
2   33

In [7]:
type(df)

pandas.core.frame.DataFrame

In [9]:
pd.__version__

'2.3.3'

In [59]:
data={
    'Name':['Madhav','Rishita','Akansha','Golu'],
    'Age':[33,34,31,29],
    'Salary':[80000,70000,150000,900000]
}

In [60]:
df=pd.DataFrame(data)

In [61]:
#2.Basic DataFrame Understanding
df.head()

      Name  Age  Salary
0   Madhav   33   80000
1  Rishita   34   70000
2  Akansha   31  150000
3     Golu   29  900000

In [62]:
df.tail(1)

   Name  Age  Salary
3  Golu   29  900000

In [63]:
df.shape

(4, 3)

In [64]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [65]:
df.rename(columns={'Salary':'Monthly_Salary'},inplace=True)

In [66]:
df

      Name  Age  Monthly_Salary
0   Madhav   33           80000
1  Rishita   34           70000
2  Akansha   31          150000
3     Golu   29          900000

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [68]:
df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   31.750000   300000.000000
std     2.217356   401580.211996
min    29.000000    70000.000000
25%    30.500000    77500.000000
50%    32.000000   115000.000000
75%    33.250000   337500.000000
max    34.000000   900000.000000

In [69]:
#Save and load data from csv

In [71]:
df2=df.to_csv('Test_data.csv') #export dataframe

In [72]:
load_df=pd.read_csv('Test_data.csv') #import dataframe

In [74]:
load_df

   Unnamed: 0     Name  Age  Monthly_Salary
0           0   Madhav   33           80000
1           1  Rishita   34           70000
2           2  Akansha   31          150000
3           3     Golu   29          900000

In [75]:
#4.Rows & Columns- Selection

In [76]:
df[['Name']]

      Name
0   Madhav
1  Rishita
2  Akansha
3     Golu

In [79]:
df[['Name','Monthly_Salary']]

      Name  Monthly_Salary
0   Madhav           80000
1  Rishita           70000
2  Akansha          150000
3     Golu          900000

In [80]:
#select rows
#select label based indexing 
df.loc[(df.Name=="Madhav") & (df.Monthly_Salary>50000)]

     Name  Age  Monthly_Salary
0  Madhav   33           80000

In [81]:
#iloc-integer based indexing 
df.iloc[0]

Name              Madhav
Age                   33
Monthly_Salary     80000
Name: 0, dtype: object

In [82]:
df.iloc[0:2] #[start:stop:step]

      Name  Age  Monthly_Salary
0   Madhav   33           80000
1  Rishita   34           70000

In [83]:
df.loc[0:2]

      Name  Age  Monthly_Salary
0   Madhav   33           80000
1  Rishita   34           70000
2  Akansha   31          150000

In [84]:
#filer DataFrame
df

      Name  Age  Monthly_Salary
0   Madhav   33           80000
1  Rishita   34           70000
2  Akansha   31          150000
3     Golu   29          900000

In [85]:
df['Age']>30

0     True
1     True
2     True
3    False
Name: Age, dtype: bool

In [86]:
df_Age=df[df['Age']>30]

In [87]:
df_Age

      Name  Age  Monthly_Salary
0   Madhav   33           80000
1  Rishita   34           70000
2  Akansha   31          150000

In [88]:
df[(df['Age']>=30) & (df['Monthly_Salary']>100000)]

      Name  Age  Monthly_Salary
2  Akansha   31          150000

In [89]:
df.where((df['Age']>=30))

      Name   Age  Monthly_Salary
0   Madhav  33.0         80000.0
1  Rishita  34.0         70000.0
2  Akansha  31.0        150000.0
3      NaN   NaN             NaN

In [90]:
#Rows & Columns operation(delete,update,add)

In [91]:
#add new column
df['Team']=['CEO','HR','CTO','DA']

In [92]:
df

      Name  Age  Monthly_Salary Team
0   Madhav   33           80000  CEO
1  Rishita   34           70000   HR
2  Akansha   31          150000  CTO
3     Golu   29          900000   DA

In [93]:
df['Bonus']=df['Monthly_Salary']*0.2

In [94]:
df

      Name  Age  Monthly_Salary Team     Bonus
0   Madhav   33           80000  CEO   16000.0
1  Rishita   34           70000   HR   14000.0
2  Akansha   31          150000  CTO   30000.0
3     Golu   29          900000   DA  180000.0

In [97]:
#add new row
df.loc[len(df)]=['ABC',33,700000,'IT',2000]

In [98]:
df

      Name  Age  Monthly_Salary Team     Bonus
0   Madhav   33           80000  CEO   16000.0
1  Rishita   34           70000   HR   14000.0
2  Akansha   31          150000  CTO   30000.0
3     Golu   29          900000   DA  180000.0
4      ABC   33          700000   IT    2000.0

In [99]:
#update values-using index name
df.loc[0,'Monthly_Salary']=950000
df

      Name  Age  Monthly_Salary Team     Bonus
0   Madhav   33          950000  CEO   16000.0
1  Rishita   34           70000   HR   14000.0
2  Akansha   31          150000  CTO   30000.0
3     Golu   29          900000   DA  180000.0
4      ABC   33          700000   IT    2000.0

In [101]:
#update values-using column value
df.loc[df.Name=="Madhav","Salary"]=90000
df

      Name  Age  Monthly_Salary Team     Bonus   Salary
0   Madhav   33          950000  CEO   16000.0  90000.0
1  Rishita   34           70000   HR   14000.0      NaN
2  Akansha   31          150000  CTO   30000.0      NaN
3     Golu   29          900000   DA  180000.0      NaN
4      ABC   33          700000   IT    2000.0      NaN

In [102]:
#delete value - row and column values

In [103]:
df.drop(df[df.Name=="ABC"].index)  #DROP ROW,AXIS=0

      Name  Age  Monthly_Salary Team     Bonus   Salary
0   Madhav   33          950000  CEO   16000.0  90000.0
1  Rishita   34           70000   HR   14000.0      NaN
2  Akansha   31          150000  CTO   30000.0      NaN
3     Golu   29          900000   DA  180000.0      NaN

In [105]:
df[df.Name=="ABC"]

  Name  Age  Monthly_Salary Team   Bonus  Salary
4  ABC   33          700000   IT  2000.0     NaN

In [108]:
df.drop('Bonus',axis=1)

      Name  Age  Monthly_Salary Team   Salary
0   Madhav   33          950000  CEO  90000.0
1  Rishita   34           70000   HR      NaN
2  Akansha   31          150000  CTO      NaN
3     Golu   29          900000   DA      NaN
4      ABC   33          700000   IT      NaN

In [109]:
df.drop(1,axis=0)

      Name  Age  Monthly_Salary Team     Bonus   Salary
0   Madhav   33          950000  CEO   16000.0  90000.0
2  Akansha   31          150000  CTO   30000.0      NaN
3     Golu   29          900000   DA  180000.0      NaN
4      ABC   33          700000   IT    2000.0      NaN

In [111]:
df.sort_values('Monthly_Salary') #by default=ascending values

      Name  Age  Monthly_Salary Team     Bonus   Salary
1  Rishita   34           70000   HR   14000.0      NaN
2  Akansha   31          150000  CTO   30000.0      NaN
4      ABC   33          700000   IT    2000.0      NaN
3     Golu   29          900000   DA  180000.0      NaN
0   Madhav   33          950000  CEO   16000.0  90000.0

In [113]:
#7 working with date value
df['DOJ']=['2024-01-01','2024-01-15','2024-03-28','2024-03-03','2024-02-02']

In [114]:
df

      Name  Age  Monthly_Salary Team     Bonus   Salary         DOJ
0   Madhav   33          950000  CEO   16000.0  90000.0  2024-01-01
1  Rishita   34           70000   HR   14000.0      NaN  2024-01-15
2  Akansha   31          150000  CTO   30000.0      NaN  2024-03-28
3     Golu   29          900000   DA  180000.0      NaN  2024-03-03
4      ABC   33          700000   IT    2000.0      NaN  2024-02-02

In [116]:
df['DOJ'].dtype

dtype('O')

In [117]:
df['DOJ']=pd.to_datetime(df['DOJ'])

In [119]:
df['DOJ'].dtype

dtype('<M8[ns]')

In [120]:
df1=df

In [122]:
df1['DOJ2']=['01-01-2025','03-03-2025','06-06-2024','02-02-2025','04-04-2025']

In [123]:
df1['DOJ2'].dtype

dtype('O')

In [127]:
df1['DOJ2']=pd.to_datetime(df1['DOJ2'],format='%d-%m-%Y')

ValueError: time data "01_01_2025" doesn't match format "%d-%m-%Y", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [128]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'])

C:\Users\Chaitanya\AppData\Local\Temp\ipykernel_14808\471760167.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df1['DOJ2'] = pd.to_datetime(df1['DOJ2'])

DateParseError: Unknown datetime string format, unable to parse: 01_01_2025, at position 0

In [129]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'], format='%d-%m-%Y', errors='coerce')

In [130]:
df1

      Name  Age  Monthly_Salary Team     Bonus   Salary        DOJ       DOJ2
0   Madhav   33          950000  CEO   16000.0  90000.0 2024-01-01        NaT
1  Rishita   34           70000   HR   14000.0      NaN 2024-01-15 2025-03-03
2  Akansha   31          150000  CTO   30000.0      NaN 2024-03-28 2024-06-06
3     Golu   29          900000   DA  180000.0      NaN 2024-03-03 2025-02-02
4      ABC   33          700000   IT    2000.0      NaN 2024-02-02 2025-04-04

In [131]:
df1['DOJ2'].dtype

dtype('<M8[ns]')

In [132]:
df=df.drop('DOJ2',axis=1)

In [133]:
df

      Name  Age  Monthly_Salary Team     Bonus   Salary        DOJ
0   Madhav   33          950000  CEO   16000.0  90000.0 2024-01-01
1  Rishita   34           70000   HR   14000.0      NaN 2024-01-15
2  Akansha   31          150000  CTO   30000.0      NaN 2024-03-28
3     Golu   29          900000   DA  180000.0      NaN 2024-03-03
4      ABC   33          700000   IT    2000.0      NaN 2024-02-02

In [134]:
#extract year,month,week,daily
df['DOJ'].dt.year

0    2024
1    2024
2    2024
3    2024
4    2024
Name: DOJ, dtype: int32

In [135]:
df['DOJ'].dt.month

0    1
1    1
2    3
3    3
4    2
Name: DOJ, dtype: int32

In [136]:
df['DOJ'].dt.day

0     1
1    15
2    28
3     3
4     2
Name: DOJ, dtype: int32

In [137]:
df['DOJ'].dt.day_name()

0      Monday
1      Monday
2    Thursday
3      Sunday
4      Friday
Name: DOJ, dtype: object

In [138]:
df['Month']=df['DOJ'].dt.month

In [139]:
df

      Name  Age  Monthly_Salary Team     Bonus   Salary        DOJ  Month
0   Madhav   33          950000  CEO   16000.0  90000.0 2024-01-01      1
1  Rishita   34           70000   HR   14000.0      NaN 2024-01-15      1
2  Akansha   31          150000  CTO   30000.0      NaN 2024-03-28      3
3     Golu   29          900000   DA  180000.0      NaN 2024-03-03      3
4      ABC   33          700000   IT    2000.0      NaN 2024-02-02      2

In [140]:
df['DOJ']+pd.Timedelta(90)

0   2024-01-01 00:00:00.000000090
1   2024-01-15 00:00:00.000000090
2   2024-03-28 00:00:00.000000090
3   2024-03-03 00:00:00.000000090
4   2024-02-02 00:00:00.000000090
Name: DOJ, dtype: datetime64[ns]

In [141]:
df

      Name  Age  Monthly_Salary Team     Bonus   Salary        DOJ  Month
0   Madhav   33          950000  CEO   16000.0  90000.0 2024-01-01      1
1  Rishita   34           70000   HR   14000.0      NaN 2024-01-15      1
2  Akansha   31          150000  CTO   30000.0      NaN 2024-03-28      3
3     Golu   29          900000   DA  180000.0      NaN 2024-03-03      3
4      ABC   33          700000   IT    2000.0      NaN 2024-02-02      2

In [ ]:
#HANDLING MISSING VALUES

In [142]:
df.isnull()

    Name    Age  Monthly_Salary   Team  Bonus  Salary    DOJ  Month
0  False  False           False  False  False   False  False  False
1  False  False           False  False  False    True  False  False
2  False  False           False  False  False    True  False  False
3  False  False           False  False  False    True  False  False
4  False  False           False  False  False    True  False  False

In [144]:
import numpy as np
df.loc[df.Name=='ABC']=np.nan

In [145]:
df.isnull()

    Name    Age  Monthly_Salary   Team  Bonus  Salary    DOJ  Month
0  False  False           False  False  False   False  False  False
1  False  False           False  False  False    True  False  False
2  False  False           False  False  False    True  False  False
3  False  False           False  False  False    True  False  False
4   True   True            True   True   True    True   True   True

In [146]:
df.isnull().sum()

Name              1
Age               1
Monthly_Salary    1
Team              1
Bonus             1
Salary            4
DOJ               1
Month             1
dtype: int64

In [147]:
df.fillna(0)

,Name,Age,Monthly_Salary,Team,Bonus,Salary,DOJ,Month
0,Madhav,33.0,950000.0,CEO,16000.0,90000.0,2024-01-01 00:00:00,1.0
1,Rishita,34.0,70000.0,HR,14000.0,0.0,2024-01-15 00:00:00,1.0
2,Akansha,31.0,150000.0,CTO,30000.0,0.0,2024-03-28 00:00:00,3.0
3,Golu,29.0,900000.0,DA,180000.0,0.0,2024-03-03 00:00:00,3.0
4,0,0.0,0.0,0,0.0,0.0,0,0.0

In [ ]:
#9.group by and aggregation

In [148]:
df['Team'].value_counts()

Team
CEO    1
HR     1
CTO    1
DA     1
Name: count, dtype: int64

In [150]:
df[df['Month']==1].value_counts()

Name    Age   Monthly_Salary  Team  Bonus    Salary   DOJ         Month
Madhav  33.0  950000.0        CEO   16000.0  90000.0  2024-01-01  1.0      1
Name: count, dtype: int64

In [152]:
df.groupby('Month')['Salary'].sum()   ##aggregation based on group by

Month
1.0    90000.0
3.0        0.0
Name: Salary, dtype: float64

In [153]:
df.groupby('Month')['Salary']

In [154]:
df.groupby('Month').agg({'Salary':'mean','Name':'count'})

        Salary  Name
Month
1.0    90000.0     2
3.0        NaN     2

In [155]:
##concatenate and merge dataframe(JOINS)
df1=pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [159]:
df2=pd.DataFrame({'ID':[1,2,2,4],'Score':['90','77','88','99']})
df2

   ID Score
0   1    90
1   2    77
2   2    88
3   4    99

In [160]:
pd.concat([df1,df2],axis=0) #vertical / top on top / row level join

   ID Name Score
0   1    A   NaN
1   2    B   NaN
2   3    C   NaN
0   1  NaN    90
1   2  NaN    77
2   2  NaN    88
3   4  NaN    99

In [161]:
pd.concat([df1,df2],axis=1) #horizontal / side by side / column level join

    ID Name  ID Score
0  1.0    A   1    90
1  2.0    B   2    77
2  3.0    C   2    88
3  NaN  NaN   4    99

In [162]:
pd.merge(df1,df2,how='inner',on='ID')

   ID Name Score
0   1    A    90
1   2    B    77
2   2    B    88

In [ ]:
#AI AND CHATGPT

In [163]:
df

      Name   Age  Monthly_Salary Team     Bonus   Salary        DOJ  Month
0   Madhav  33.0        950000.0  CEO   16000.0  90000.0 2024-01-01    1.0
1  Rishita  34.0         70000.0   HR   14000.0      NaN 2024-01-15    1.0
2  Akansha  31.0        150000.0  CTO   30000.0      NaN 2024-03-28    3.0
3     Golu  29.0        900000.0   DA  180000.0      NaN 2024-03-03    3.0
4      NaN   NaN             NaN  NaN       NaN      NaN        NaT    NaN

In [165]:
df[(df['DOJ'].dt.month==1) & (df['Salary']>70000)]

     Name   Age  Monthly_Salary Team    Bonus   Salary        DOJ  Month
0  Madhav  33.0        950000.0  CEO  16000.0  90000.0 2024-01-01    1.0

In [166]:
df.query("Month==1 & Salary>70000")

     Name   Age  Monthly_Salary Team    Bonus   Salary        DOJ  Month
0  Madhav  33.0        950000.0  CEO  16000.0  90000.0 2024-01-01    1.0